### PR TITLE
fix: `rpcUrl` should be used when provided in the `getStakingContract` function

### PR DESCRIPTION
**Pull request by Ansonhkg**
# Description

See title

### CODE REVIEW

**Review by MaximusHaximus — APPROVED** [review]
:+1: Let's do this

**Review by glitch003 — APPROVED** [review]
makes sense to me, thx

**Review by MaximusHaximus — APPROVED** [review]
<3 GTG. I like the removal of assigning to function argument :)

**Comment by FedericoAmura** [comment]
Liking this PR ❤️ 😂

**Pull request merged**
