### PR TITLE
updated README files

### PR DESCRIPTION
**Pull request by phoenixx11**
-removed references to Vanilla Js as it was not being used -verified all functionalities described in README files are working -added missing details and clarified existing info in the README files

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
u
- updated the read me files with the changes 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [x] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Ansonhkg** [comment]
please also make sure the root readme.md is tested and updated @phoenixx11

**Review by Ansonhkg — CHANGES_REQUESTED** [review]
please also make sure the root readme.md is tested and updated @phoenixx11

**Comment by phoenixx11** [comment]
Sure !

**Comment by phoenixx11** [comment]
Tested!Done

**Comment by Ansonhkg** [comment]
> Tested!Done

Has every single command been checked on the README.md?

**Comment by Ansonhkg** [comment]
Closing this as it's been inactive.

**Pull request closed without merging**
