### PR TITLE
feat: remove jszip and compression utilities

### PR DESCRIPTION
**Pull request by FedericoAmura**
# Description

This PR removes the compression responsibility from the encryption package and the sdk overall to reduce the bundle size and delegate that responsibility to the consumers that need it

See https://github.com/LIT-Protocol/js-sdk/pull/621#issuecomment-2348769396 for optimisation results

# Changelog
- removed the following functions from `@lit-protocol/encryption` package, and their tests
  - `encryptZip`
  - `zipAndEncryptString`
  - `zipAndEncryptFiles`
  - `encryptFileAndZipWithMetadata`
  - `decryptToZip` 
  - `decryptZipFileWithMetadata`
- removed jszip from bundle

# Migration guide
If you are using any of these functions:
- `encryptZip`
- `zipAndEncryptString`
- `zipAndEncryptFiles`
- `encryptFileAndZipWithMetadata`
- `decryptToZip` 
- `decryptZipFileWithMetadata`
You now have to handle compression yourself and encrypt before or after it

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Existing tests still pass

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by joshLong145 — COMMENTED** [review]
Nice! if you have the time publishing a test build and reporting the bundle size of `LitNodeClient` and `LitNodeClientNodejs` would be awesome.

**Comment by FedericoAmura** [comment]
> Nice! if you have the time publishing a test build and reporting the bundle size of `LitNodeClient` and `LitNodeClientNodejs` would be awesome.

What I can quickly say using bundlephobia, is that removing jszip should release around these % of each package (based on current published version)
encryption ~4%
lit-node-client & lit-node-client ~2.8%

**Review by Ansonhkg — CHANGES_REQUESTED** [review]
https://github.com/LIT-Protocol/js-sdk/pull/621#issuecomment-2343906911

**Comment by Ansonhkg** [comment]
# Here's the result from Bundlephobia

## 6.4.2

image

image


## 6.4.2-pr-621 (Published from this PR)
image

image

**Review by Ansonhkg — APPROVED** [review]
LGTM!

**Pull request merged**
