### PR TITLE
fix: Workaround for ethers.js bug in webpack environments

### PR DESCRIPTION
**Pull request by joshdchang**
# Description

I was getting the following issue when trying to connect in a nodejs server-side webpack environment (in Next.js):
```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
```

After doing some searching and testing, I figured out it was an bug from ethers.js with webpack. I tried the workaround from [https://github.com/ethers-io/ethers.js/issues/3536#issuecomment-1323302238](https://github.com/ethers-io/ethers.js/issues/3536#issuecomment-1323302238) and it fixed the issue. This PR only changes one line of code.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Try running it in Next.js server side with and without this change. You will see the difference.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Ansonhkg — COMMENTED** [review]
Thanks for digging into this! 

Could you change the `JsonRpcProvider` to `StaticJsonRpcProvider`? 

We have just got this PR up (https://github.com/LIT-Protocol/js-sdk/pull/537) which could half to RPC request time by simply changing it to static

**Comment by joshdchang** [comment]
> Could you change the `JsonRpcProvider` to `StaticJsonRpcProvider`?
> 
> We have just got this PR up (#537) which could half to RPC request time by simply changing it to static

Sure let me try

**Comment by joshdchang** [comment]
@Ansonhkg Okay I changed it to `StaticJsonRpcProvider` and it seems to work well.

**Review by Ansonhkg — APPROVED** [review]
This LGTM. @MaximusHaximus WDYT?

**Review by MaximusHaximus — CHANGES_REQUESTED** [review]
Thanks so much for the contribution @joshdchang :D We really appreciate it.

FYI, this change is a little bit different than you described @Ansonhkg -- this is literally controlling how `fetch()` is called rather than controlling whether `chainId` is checked (which was the difference between `JSONRPCProvider` and `StaticJSONRPCProvider`)

From the docs:

### **connection.skipFetchSetup ⇒ boolean**
_Normally a connection will specify the default values for a connection such as CORS-behavior and caching policy, to ensure compatibility across platforms. On some services, such as Cloudflare Workers, specifying any value (inclluding the default values) will cause failure. Setting this to true will prevent any values being passed to the underlying API.```_

I think it should be fine to add this argument to the `JSONRPCProvider` construction, but we create these providers in a bunch of different places, so while this PR as currently written would fix using the contracts SDK _directly_, consumers of the SDK will still run into this error in other places in the SDK where we construct the `JSONRPCProvider` on their behalf - likely just a few minutes later down their exploration of the JS SDK. 

For your reference, every place that we need the new argument added are the same exact lines that were changed from `JSONRPCProvider` to `StaticJSONRPCProvider` in #537, plus one additional place that I didn't change in that PR because we couldn't use the StaticJSONRPCProvider for generic chains where we wouldn't necessarily be able to skip the `chainId` pre-check behaviour [here](https://github.com/LIT-Protocol/js-sdk/blob/89b24c889b0b14830684fe581095ca9d8455595a/packages/misc/src/lib/misc.ts#L630)

Are you OK to make that change @joshdchang?

**Comment by joshdchang** [comment]
> Are you OK to make that change @joshdchang?

Hi, thanks for this! Do you want me to change it to StaticJSONRPCProvider in all the locations as well? This would overlap substantially with #537 and might lead to merge conflicts. Maybe this is best done in one PR?

**Comment by MaximusHaximus** [comment]
> > Are you OK to make that change @joshdchang?
> 
> Hi, thanks for this! Do you want me to change it to StaticJSONRPCProvider in all the locations as well? This would overlap substantially with #537 and might lead to merge conflicts. Maybe this is best done in one PR?

Sorry for the delayed response, and thanks so much for contributing!
We've landed the JsonStaticRPCProvider PR now, so you're GTG without needing to worry about conflicts :)

**Comment by FedericoAmura** [comment]
Replacing this with https://github.com/LIT-Protocol/js-sdk/pull/646 which has the changes needed on all the providers. Thanks @joshdchang !!!

**Pull request closed without merging**
