### PR TITLE
Ref/remove execute with retry

### PR DESCRIPTION
**Pull request by joshLong145**
# Description

Removes 'executeWithRetry` as we are more stable when performing
- `executeJs`
- `pkpSign`
- `decrypt`
- `runOnTargetNodes`
- `signSessionKey`

**Note: retrying internal network calls which are required for stand up will be added back in an up coming pr.**

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with `local-tests` 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Ansonhkg — APPROVED** [review]
nice!

Update:
https://github.com/LIT-Protocol/js-sdk/pull/497#pullrequestreview-2099492136

**Review by Ansonhkg — COMMENTED** [review]
There's a build error with `RetryTolerance` in the CI, i think we need to remove it from `misc.ts`

```
Compiling TypeScript files for project "misc"...
packages/misc/src/lib/misc.ts:30:3 - error TS2305: Module '"@lit-protocol/types"' has no exported member 'RetryTolerance'.

30   RetryTolerance,
     ~~~~~~~~~~~~~~

: 
```

**Review by Ansonhkg — CHANGES_REQUESTED** [review]
There's a build error with `RetryTolerance` in the CI, i think we need to remove it from `misc.ts`

```
Compiling TypeScript files for project "misc"...
packages/misc/src/lib/misc.ts:30:3 - error TS2305: Module '"@lit-protocol/types"' has no exported member 'RetryTolerance'.

30   RetryTolerance,
     ~~~~~~~~~~~~~~

: 
```

**Comment by joshLong145** [comment]
> There's a build error with `RetryTolerance` in the CI, i think we need to remove it from `misc.ts`
> 
> ```
> Compiling TypeScript files for project "misc"...
> packages/misc/src/lib/misc.ts:30:3 - error TS2305: Module '"@lit-protocol/types"' has no exported member 'RetryTolerance'.
> 
> 30   RetryTolerance,
>      ~~~~~~~~~~~~~~
> 
> : 
> ```

Ah missed a spot. Doing it now

**Review by Ansonhkg — DISMISSED** [review]

**Review by Ansonhkg — APPROVED** [review]

**Pull request merged**
