### PR TITLE
add multiple auth method mint to lit auth client

### PR DESCRIPTION
**Pull request by joshLong145**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
- Adds `mintPKPWithAuthMethods` allowing for multiple `auth methods` for minting with multiple auth methods, without up front parsing using helper methods.
- Fixes some places where we default to `0` as permission when minting a new pkp.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Adds new test to `e2e-nodejs`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by furkanakal** [comment]
Thanks for handling it this fast.

I think we need an analogous method for `fetchPKPsThroughRelayer()` method as well. Do we have an alternative for multiple auth methods?

**Comment by joshLong145** [comment]
> Thanks for handling it this fast.
> 
> I think we need an analogous method for `fetchPKPsThroughRelayer()` method as well. Do we have an alternative for multiple auth methods?

I think i am misunderstanding your comment. the implemented method does use the relayer as there is no other options ( which is missleading. I can update to include `relayer` so the method name becomes `mintPKPWithAuthMethodsThroughRelayer` to better indicate. I chose this name on purpose however as in the future i would like to abstract away the relayer being statically coupled to this implementation all together. So these names will likely change to indicate that it either can mint through the `relayer` or our `contracts`

**Comment by furkanakal** [comment]
Let me clarify: In addition to a minting method for multiple auth methods, we might need a method to fetch PKP for multiple auth methods (what `fetchPKPThroughRelayer()` does)

**Comment by joshLong145** [comment]
> Let me clarify: In addition to a minting method for multiple auth methods, we might need a method to fetch PKP for multiple auth methods (what `fetchPKPThroughRelayer()` does)

This is not possible as you can only fetch auth methods by a single `authMethodId` so what you are describing is not needed. 
So if registering multiple auth methods. you can only query by `1` of them.

**Comment by furkanakal** [comment]
Okay, then. Thanks!

**Review by furkanakal — DISMISSED** [review]

**Review by Ansonhkg — APPROVED** [review]
lgtm

**Pull request merged**
