### PR TITLE
change session exp default to 1 day

### PR DESCRIPTION
**Pull request by joshLong145**
# Description

Lowers the default session exp to `1 day`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
testing has been added by removing an explicit `expiration` property when generating session signatures through `getSessionSigs`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Adarsh-Kumar28 — COMMENTED** [review]
Not a functional change?

**Comment by Ansonhkg** [comment]
makes sense

**Review by Ansonhkg — DISMISSED** [review]

**Comment by joshLong145** [comment]
> Not a functional change?

What do you mean by this? The change is needed to prevent implicit expiration values from failing on generation due to maximum expiration being over the limit.

**Comment by Adarsh-Kumar28** [comment]
> > Not a functional change?
> 
> What do you mean by this? The change is needed to prevent implicit expiration values from failing on generation due to maximum expiration being over the limit.

It was already one day: `1000 * 60 * 60 * 24` @joshLong145

**Comment by joshLong145** [comment]
> > > Not a functional change?
> > 
> > 
> > What do you mean by this? The change is needed to prevent implicit expiration values from failing on generation due to maximum expiration being over the limit.
> 
> It was already one day: `1000 * 60 * 60 * 24` @joshLong145

Oh you are right. i thought there some extra zero's i personally think the new format is easier to read.

**Pull request closed without merging**
