### PR TITLE
feat: Tests for new chains on Cayenne

### PR DESCRIPTION
**Pull request by DashKash54**
# Description

Tests for new chains supported on Cayenne.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual Tests

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] Any dependent changes have been merged and published in downstream modules

1. https://github.com/LIT-Protocol/lit-assets/pull/1135
2. https://github.com/LIT-Protocol/lit_node_admin_app/pull/46

### CODE REVIEW

**Comment by joshLong145** [comment]
@DashKash54 
Are these also on `Manzano` and `Habanero` if we publish this as a `5.0.1` patch will it work on all networks?

**Comment by DashKash54** [comment]
> @DashKash54 Are these also on `Manzano` and `Habanero` if we publish this as a `5.0.1` patch will it work on all networks?

Not yet as the v0.1 release hasn't done for these networks

**Comment by joshLong145** [comment]
> > @DashKash54 Are these also on `Manzano` and `Habanero` if we publish this as a `5.0.1` patch will it work on all networks?
> 
> Not yet as the v0.1 release hasn't done for these networks

If we merge this into `master` then other networks will be able to use these additions? should we point this pr at `staging/v6` instead? So we only publish it under the `@cayenne` tag?

**Review by rahul-ramesh — APPROVED** [review]

**Comment by DashKash54** [comment]
> If we merge this into `master` then other networks will be able to use these additions? should we point this pr at `staging/v6` instead? So we only publish it under the `@cayenne` tag?

We can merge this after Habanero is deployed as it will contain these chains: https://github.com/LIT-Protocol/lit-os/blob/b5d56af53174d381fdc4de60c7a7319d506bb30a/components/common/salt/state/lit/core/blockchain/config/rpc-config.yaml#L1

**Comment by joshLong145** [comment]
@DashKash54 
can you change the base branch to `staging/v6`

**Comment by joshLong145** [comment]
@DashKash54 
Looks like ci is still running the old e2e tests, i think something is wrong with the branch. Would you be able to rebase it onto `staging/v6` or just recreate the pr off of that branch?

**Comment by joshLong145** [comment]
Closing as branch has not been updated. @DashKash54 please re open with an rebased / fresh branch as the CI is not properly running when re targeting `staging/v6`

**Pull request closed without merging**
